import { JotaiProvider } from '@/components/Providers/JotaiProvider';
import { HydrateAtoms } from '@/components/Providers/QueryClientProvider';
import 'app/globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <JotaiProvider>
          <HydrateAtoms>{children}</HydrateAtoms>
        </JotaiProvider>
      </body>
    </html>
  );
}
